version: '3.6'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1qaz2wsx
      MYSQL_DATABASE: user
      MYSQL_USER: spring-redis
      MYSQL_PASSWORD: r4cc00n
  redis:
    image: redis
    ports:
      - "6379:6379"